### ISSUE TITLE
Nothing is happeneing

### ISSUE THREAD

**Issue by ghost** [marekaf/gcp-stackdriver-logging-extract-textpayload#1]
I followed your exact instructions but I'm not seeing anything at the destination bucket.

When I use the "TESTING" section in the Cloud Function I get this error"
TypeError: Cannot read property 'bucket' of undefined at exports.logTransformer (/srv/index.js:35:40) at /worker/worker.js:825:24 at <anonymous> at process._tickDomainCallback (internal/process/next_tick.js:229:7)

I used the console to create the Function:

I choose Runtime: Node.js 8
----------------------
In the Environment section I added:
Environment variables
DEST_BUCKET_NAME -> destestexport
------------------------
I set the following configs in the Trigger section
Trigger type -> Cloud Storage
Bucket  -> bucketname
Event Type -> Finalize/Create
----------------------------
I copied the index.js and package.json and paste them at the Source
And I set 
Function to execute -> logTransformer
-------------------------

Can you let me know what I missed. I would appreciate the help.
Thanks

**Comment by ajaysourcedigital** [comment]
@MONTATICH  the function is written only when you place a file in bucket. It doesnt run directly.
